apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-k8s
  labels:
    name: flask-app-k8s
    env: dev
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app-k8s
          image: sadmanrock/flask-app:v2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
