apiVersion: v1
kind: Service
metadata:
  name: flask-app-k8s-svc
  labels:
    name: flask-app-k8s
    env: dev
    app: flask
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flask
    
